
// This file has been generated by the GUI designer. Do not modify.
namespace Cairo.R7.Anim
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.ToggleAction pauseAction;
		private global::Gtk.VBox vbox1;
		private global::Gtk.Toolbar toolbar1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.DrawingArea drawingarea1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.DrawingArea drawingarea3;
		private global::Gtk.DrawingArea drawingarea2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Cairo.R7.Anim.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.pauseAction = new global::Gtk.ToggleAction ("pauseAction", null, null, "gtk-media-pause");
			this.pauseAction.IsImportant = true;
			w1.Add (this.pauseAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "Cairo.R7.Anim.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Cairo.R7.Anim");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Cairo.R7.Anim.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar1'><toolitem name='pauseAction' action='pauseAction'/></toolbar></ui>");
			this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
			this.toolbar1.Name = "toolbar1";
			this.toolbar1.ShowArrow = false;
			this.vbox1.Add (this.toolbar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.toolbar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.drawingarea1 = new global::Gtk.DrawingArea ();
			this.drawingarea1.Name = "drawingarea1";
			this.hbox1.Add (this.drawingarea1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.drawingarea1]));
			w3.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.drawingarea3 = new global::Gtk.DrawingArea ();
			this.drawingarea3.Name = "drawingarea3";
			this.vbox2.Add (this.drawingarea3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.drawingarea3]));
			w4.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.drawingarea2 = new global::Gtk.DrawingArea ();
			this.drawingarea2.Name = "drawingarea2";
			this.vbox2.Add (this.drawingarea2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.drawingarea2]));
			w5.Position = 1;
			this.hbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
			w6.Position = 1;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w7.Position = 1;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 388;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.pauseAction.Toggled += new global::System.EventHandler (this.OnPauseActionToggled);
			this.drawingarea1.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnDrawingarea1ExposeEvent);
			this.drawingarea3.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnDrawingarea1ExposeEvent);
			this.drawingarea2.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnDrawingarea1ExposeEvent);
		}
	}
}
